version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"  # Mapeamento da porta do contêiner para a porta do host
    depends_on:
      - rabbitmq
      - database

  consumer:
    build:
      context: .
      dockerfile: Eris.Rabbit.Store.Consumer/Dockerfile
    depends_on:
      - rabbitmq
      - database

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # Porta de comunicação padrão
      - "15672:15672"  # Porta da interface de gerenciamento
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Senha do usuário root
      MYSQL_DATABASE: "eris_store"  # Nome do banco de dados
    ports:
      - "3306:3306"  # Porta do MySQL
